### ISSUE TITLE
Make interface consistent w/ `helm-grep-do-git-grep` and `helm-do-ag`

### ISSUE THREAD

**Issue by xiongtx** [cosmicexplorer/helm-rg#2]
Thanks for creating this! We're [using it](https://github.com/bbatsov/helm-projectile/pull/107) in `helm-projectile` as the Ripgrep interface, but unfortunately it's not quite the same as other search interfaces. See [this comment](https://github.com/bbatsov/helm-projectile/pull/107#issuecomment-390846400).

Here's `helm-rg`:

## `helm-rg`
![image](https://user-images.githubusercontent.com/1624090/40339835-09972576-5d31-11e8-84a1-845b7065ae53.png)

And `-grep` and `-ag` commands, from [Helm](https://github.com/emacs-helm/helm) and [`helm-ag`](https://github.com/syohex/emacs-helm-ag) respectively:

## `helm-grep-do-git-grep`

![image](https://user-images.githubusercontent.com/1624090/40339900-55532aa0-5d31-11e8-85b6-f201e9dad48b.png)

## `helm-do-ag`

![image](https://user-images.githubusercontent.com/1624090/40339927-67e8a348-5d31-11e8-8df7-bf2d0300a59b.png)

It'd be nice if `helm-rg` could follow the same design as the others for a consistent user experience!

**Comment by cosmicexplorer** [comment]
Thanks for filing this issue!

I actually just changed the display of each line to its current form last week or so. While I introduced several other "architectural" changes during that development, I will hopefully be able to copy back the previous display code and allow switching between the display modes with a `defcustom` named maybe `helm-rg--results-display-style`. I would like to keep the default value for this defcustom to use the new file/line display interface, but the other value would be a symbol maybe named `'with-file-location`. Your code could then call it as:
```elisp
(let ((helm-rg--results-display-style 'with-file-location))
  (helm-rg "" nil (list (projectile-project-root))))
```

or however else you might want to do that.

**Comment by xiongtx** [comment]
Sounds good--let me know when you'd like me to review / try it out.

**Comment by cosmicexplorer** [comment]
@xiongtx as of 2f1ea6db272311f0aae99512a1a70e3e3286393a, you should be able to use the following to achieve the desired output:
```elisp
(let ((helm-rg-prepend-file-name-line-at-top-of-matches nil)
      (helm-rg-include-file-on-every-match-line t))
  (helm-rg "" nil (list (projectile-project-root))))
```
![wow2](https://user-images.githubusercontent.com/1305167/40582429-a6a80288-612b-11e8-8e83-79718cb22723.png)

**Comment by xiongtx** [comment]
Thanks! I've [pushed a commit](https://github.com/bbatsov/helm-projectile/commit/a6a453b7a32d52f4ddd125deb88d7d81542440d2).

**Comment by cosmicexplorer** [comment]
@xiongtx Thanks for describing the issue! I couldn't think of a situation when I would want the absolute paths instead of relative paths, so a37c53f28c095164b77ce10264bf0b777316599b should do as expected, see:
![wow3](https://user-images.githubusercontent.com/1305167/40761667-785d7ab0-6451-11e8-8eb6-e71d5b7bcf7c.png)

Let me know if this seems to work for you.

**Comment by xiongtx** [comment]
Yup, that'll do it! Thanks!

**Comment by jamesnvc** [comment]
I'm finding that the last change above, to show relative paths, makes `helm-resume` not work properly, because when the search resumes it will try to resolve the relative paths to the current directory; reverting a37c53f makes it seem to work properly for me; would it be possible to make that an option or something?

**Comment by cosmicexplorer** [comment]
@jamesnvc please let me know if 2326451 (introducing `helm-rg-file-paths-in-matches-behavior`, which can be set to `'absolute`) resolves your issue, and if not, could you open a new issue? Thanks for the note!

**Comment by jamesnvc** [comment]
@cosmicexplorer perfect, that's great! Thank you very much :smile:

**Comment by cosmicexplorer** [comment]
@jamesnvc I've also seen #14 and added a test framework so it won't break so when that gets merged you may be able to revert that customization!
